# Step 1. Setup a repository dispatch
# Ref: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#repository_dispatch
name: CI/CD

on:
  repository_dispatch:

jobs:
  greeting:
    name: Say Hello world
    runs-on: ubuntu-latest
    if: ${{ github.event.client_payload.action == 'greeting' }}
    steps:
      - name: Greeting
        run: echo "Hello world, ${{github.event.client_payload.name}} 🚀"

# Step 2. Trigger an action by creating a dispatch event (https://docs.github.com/en/free-pro-team@latest/rest/repos/repos?apiVersion=2022-11-28#create-a-repository-dispatch-event)
# For example:
# curl -L \
#   -X POST \
#   -H "Accept: application/vnd.github+json" \
#   -H "Authorization: Bearer you-personal-github-token" \
#   -H "X-GitHub-Api-Version: 2022-11-28" \
#   https://api.github.com/repos/haile-vnm/github-action-examples/dispatches \
#   -d '{"event_type":"greeting","client_payload":{"action": "greeting", "name":"Hai Le"}}'
